version: '3.8'

services:
  # Main application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/inventory
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../src:/app/src
      - ../package.json:/app/package.json

  # MongoDB service
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis service
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  # Test service
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: npm run test
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/inventory_test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
    driver: local